application: busvlru
version: 1
runtime: python27
threadsafe: true
api_version: 1
skip_files: |
 (.*/svn/.*)|
 (.*/Thumbs\.db)

builtins:
- remote_api: on

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: style/favicon.ico
  upload: style/favicon.ico

- url: /.*
  script: app.application
